In [2]:
import pandas as pd

In [3]:
car = pd.read_csv("cats_data.csv")

In [4]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           4340 non-null   object
 1   year           4340 non-null   int64 
 2   selling_price  4340 non-null   int64 
 3   km_driven      4340 non-null   int64 
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB


In [5]:
car.shape

(4340, 8)

In [6]:
car.head()

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [7]:
car_copy = car.copy()

In [8]:
car_copy

name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
0     Petrol  Individual       Manual   First Owner  
1     Petrol  Individual       Manual   First Owner  
2     Diesel  Individual       Manual   First Owner  
3     Petrol  Individual       Manual   First Owner  
4     Diesel  Individual       Manual  Second Owner  
...      ...         ...          ...           ...  
4335  Diesel  Individual       Manual  Second Owner  
4336  Diesel  Individual       Manual  Second Owner  
4337  Petrol  Individual       Manual  Second Owner  
4338  Diesel  Individual       Manual   First Owner  
4339  Petrol  Individual       Manual   First Owner  

[4340 rows x 8 columns]

In [9]:
car = car.drop(columns=["seller_type","transmission","owner"])

In [10]:
car


name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel  
0     Petrol  
1     Petrol  
2     Diesel  
3     Petrol  
4     Diesel  
...      ...  
4335  Diesel  
4336  Diesel  
4337  Petrol  
4338  Diesel  
4339  Petrol  

[4340 rows x 5 columns]

In [11]:
car["year"].unique()

array([2007, 2012, 2017, 2014, 2016, 2015, 2018, 2019, 2013, 2011, 2010,
       2009, 2006, 1996, 2005, 2008, 2004, 1998, 2003, 2002, 2020, 2000,
       1999, 2001, 1995, 1997, 1992], dtype=int64)

In [12]:
car["selling_price"].unique()

array([  60000,  135000,  600000,  250000,  450000,  140000,  550000,
        240000,  850000,  365000,  260000, 1650000,  585000, 1195000,
        390000, 1964999, 1425000,  975000, 1190000,  930000,  525000,
       1735000, 1375000,  900000, 1300000, 1400000,  229999, 1550000,
       1250000,  625000, 1050000,  560000,  290000,  275000,  411000,
        150000,  500000,  100000,  725000,  401000,  750000,  310000,
        665000,  465000,  160000,  675000,  300000,   70000,  151000,
        280000,  350000,  570000,  125000,  130000,  925000,  200000,
        248000,   80000,  650000,  495000,  371000, 1025000, 8150000,
        325000, 1470000, 2800000,  210000, 1150000, 4500000, 2750000,
       1975000,  175000, 2500000,  628000,  399000,  315000,  780000,
        434000,  690000,  555000,  120000,  165000,   95000,  800000,
        840000,  490000,  400000, 1000000,  530000,   40000,   75000,
        540000,  700000,  430000,   65000,  195000,  170000,  225000,
         99000,  620

In [13]:
car["fuel"].unique()

array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [14]:
car["km_driven"].unique()

array([ 70000,  50000, 100000,  46000, 141000, 125000,  25000,  60000,
        78000,  35000,  24000,   5000,  33000,  28000,  59000,   4500,
       175900,  14500,  15000,  33800, 130400,  80000,  10000, 119000,
        75800,  40000,  74000,  64000, 120000,  79000,  18500,  10200,
        29000,  90000,  73300,  92000,  66764, 350000, 230000,  31000,
        39000, 166000, 110000,  54000,  63000,  76000,  11958,  20000,
         9000,   6500,  58000,  62200,  34000,  53000,  49000,  63500,
         9800,  13000,  21000,  29173,  48000,  30000,  87000,  16000,
        79350,  81000,   3600,  14272,  49213,  57000,   3240, 114000,
        53772, 140000, 175000,  36000, 155500,  23000,  22155,  78380,
       150000,  80362,  55000,   1136,  43000,   2650, 115962,  65000,
        56000, 213000, 139000, 160000, 163000,  32000,  52000,  11240,
        66000,  26500,  72000,  44000, 130000, 195000, 155000,   4000,
        41000,  10832,  14681,  51000, 200000,  19600,  46730,  21170,
      

In [15]:
x = car.drop(columns="selling_price")
y = car["selling_price"]

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size = 0.2)

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [18]:
ohe = OneHotEncoder()
ohe.fit(x[["name","year","km_driven","fuel"]])

OneHotEncoder()

In [19]:
ohe.categories_


[array(['Ambassador CLASSIC 1500 DSL AC', 'Ambassador Classic 2000 Dsz',
        'Ambassador Grand 1800 ISZ MPFI PW CL', ...,
        'Volvo XC 90 D5 Inscription BSIV', 'Volvo XC60 D3 Kinetic',
        'Volvo XC60 D5 Inscription'], dtype=object),
 array([1992, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
        2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
        2016, 2017, 2018, 2019, 2020], dtype=int64),
 array([     1,    101,   1000,   1001,   1010,   1100,   1111,   1136,
          1200,   1250,   1300,   1400,   1440,   1452,   1500,   1700,
          1758,   1950,   2000,   2020,   2417,   2500,   2650,   2769,
          3000,   3240,   3600,   3700,   3917,   4000,   4400,   4432,
          4500,   4637,   5000,   5007,   5166,   5200,   5400,   5550,
          5800,   6000,   6480,   6500,   6590,   7000,   7104,   7300,
          7600,   7658,   7900,   8000,   8352,   8500,   9000,   9161,
          9400,   9422,   9500,   9528,   9700, 

In [20]:
column_trans = make_column_transformer((OneHotEncoder(categories = ohe.categories_),["name","year","km_driven","fuel"]),remainder = "passthrough")

In [21]:
lr = LinearRegression()

In [22]:
pipe = make_pipeline(column_trans,lr)

In [23]:
pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Ambassador CLASSIC 1500 DSL AC', 'Ambassador Classic 2000 Dsz',
       'Ambassador Grand 1800 ISZ MPFI PW CL', ...,
       'Volvo XC 90 D5 Inscription BSIV', 'Volvo XC60 D3 Kinetic',
       'Volvo XC60 D5 Inscription'], dtype=object),
                                                                            array([1992, 1995, 1996, 19...
       210000, 212814, 213000, 217871, 218000, 220000, 221000, 222252,
       222435, 223000, 223660, 224642, 230000, 234000, 235000, 238000,
       240000, 244000, 245244, 250000, 256000, 260000, 267000, 270000,
       280000, 295000, 296823, 300000, 312000, 347089, 350000, 400000,
       560000, 806599], dtype=int64),
                                                                            array(['CNG', 'Diesel', 'Electric', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'year', 'km_driven',
                                                   'fuel'])])),
                ('linearregression', LinearRegression())])

In [24]:
Y_pred = pipe.predict(X_test)

In [25]:
r2_score(Y_test,Y_pred)

0.7409541929139727

In [26]:
scores = []
for i in range(1000):
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_pred = pipe.predict(x_test)
    scores.append(r2_score(y_test,y_pred))

In [27]:
import numpy as np
np.argmax(scores)

531

In [28]:
scores[531]

0.9036980550683014

In [29]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = np.argmax(scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans,lr)
pipe.fit(x_train,y_train)
y_pred = pipe.predict(x_test)
r2_score(y_test,y_pred)

0.9036980550683014

In [30]:
import pickle
pickle.dump(pipe,open("final_model.pkl","wb"))

In [33]:
pipe.predict(pd.DataFrame([["Hyundai Verna 1.6 SX",2012,10000,"Diesel",]],columns = x_test.columns))

array([547123.43892648])

In [32]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
pipe2 = make_pipeline(column_trans,rf)
pipe2.fit(x_train,y_train)
y_pred2 = pipe2.predict(x_test)
r2_score(y_test,y_pred2)

0.7999928993222605

In [35]:
x_test.columns


Index(['name', 'year', 'km_driven', 'fuel'], dtype='object')

In [36]:
pickle.dump(pipe2,open("random_forest.pkl","wb"))